<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
    xmlns:Q1="urn://grupoaval.com/xsd/ifx/"
    xmlns:Q2="urn://grupoaval.com/xsd/ifx/v2/"
    xmlns:Q3="urn://grupoaval.com/xsd/ifx/v1/"
    xmlns:aval="urn://grupoaval.com/xsd/ifx/"
    xmlns:avalv2="urn://grupoaval.com/xsd/ifx/v2/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:v1="urn://grupoaval.com/prodschnsmngt/v1/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    name="SrvOverdraftLine_ModifyOverdraftLine"
    targetNamespace="urn://grupoaval.com/prodschnsmngt/v1/">
  <wsdl:types>
    <xsd:schema targetNamespace="urn://grupoaval.com/prodschnsmngt/v1/" xmlns:Q1="urn://grupoaval.com/xsd/ifx/" xmlns:v1="urn://grupoaval.com/prodschnsmngt/v1/" xmlns:Q2="urn://grupoaval.com/xsd/ifx/v2/">
      <xsd:import namespace="urn://grupoaval.com/xsd/ifx/" />
      <xsd:import namespace="urn://grupoaval.com/xsd/ifx/v2/" />
      <xsd:element name="ModifyOverdraftLine">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="in" type="xsd:string" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="ModifyOverdraftLineRs" type="v1:ModifyOverdraftLineRs_Type" />
      <xsd:element name="ModifyOverdraftLineRq" type="v1:ModifyOverdraftLineRq_Type" />
      <xsd:element name="ModifyOverdraftLineResponse" type="v1:ModifyOverdraftLineResponse_Type" />
      <xsd:element name="ModifyOverdraftLineRequest" type="v1:ModifyOverdraftLineRequest_Type" />
      <xsd:complexType name="ModifyOverdraftLineRq_Type">
        <xsd:sequence>
          <xsd:element minOccurs="1" ref="Q1:RqUID" />
          <xsd:element minOccurs="1" ref="Q1:MsgRqHdr" />
          <xsd:element minOccurs="1" ref="Q1:CustId" />
          <xsd:element minOccurs="0" ref="Q1:ChkNum" />
          <xsd:element minOccurs="0" ref="Q2:Code" />
          <xsd:element minOccurs="0" ref="Q1:CurCode" />
          <xsd:element minOccurs="0" ref="Q1:MaxAmt" />
          <xsd:element minOccurs="0" ref="Q1:Amt" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="ModifyOverdraftLineRs_Type">
        <xsd:sequence>
          <xsd:element minOccurs="1" ref="Q1:Status" />
          <xsd:element minOccurs="1" ref="Q1:RqUID" />
          <xsd:element minOccurs="0" ref="Q1:MsgRqHdr" />
          <xsd:element minOccurs="0" ref="Q1:MsgRsHdr" />
          <xsd:element minOccurs="0" ref="Q1:CustId" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="ModifyOverdraftLineResponse_Type">
        <xsd:sequence>
          <xsd:element ref="v1:ModifyOverdraftLineRs" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="ModifyOverdraftLineRequest_Type">
        <xsd:sequence>
          <xsd:element ref="v1:ModifyOverdraftLineRq" />
        </xsd:sequence>
      </xsd:complexType>
    </xsd:schema>
    <xsd:schema attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="urn://grupoaval.com/xsd/ifx/" xmlns:aval="urn://grupoaval.com/xsd/ifx/" xmlns:avalv2="urn://grupoaval.com/xsd/ifx/v2/" xmlns:Q1="urn://grupoaval.com/xsd/ifx/">
      <xsd:import namespace="urn://grupoaval.com/xsd/ifx/v2/" />
      <xsd:element name="LastName" type="aval:LastName_Type" />
      <xsd:element name="EffDt" type="xsd:dateTime" />
      <xsd:element name="BranchName" type="xsd:string" />
      <xsd:element name="Amt" type="xsd:decimal" />
      <xsd:element name="MaxAmt" type="xsd:decimal" />
      <xsd:element name="BankIdType" type="aval:OpenEnum_Type" />
      <xsd:element name="ServerStatusCode" type="xsd:string" />
      <xsd:element name="RemainRec" type="xsd:boolean" />
      <xsd:element name="IssDt" type="xsd:string" />
      <xsd:element name="ServerStatusDesc" type="xsd:string" />
      <xsd:element name="IPAddr" type="xsd:string" />
      <xsd:element name="Name" type="xsd:string" />
      <xsd:element name="StatusCode" type="xsd:long" />
      <xsd:element name="BranchId" type="xsd:string" />
      <xsd:element name="CustPermId" type="xsd:string" />
      <xsd:element name="Org" type="xsd:string" />
      <xsd:element name="RefId" type="aval:Identifier_Type" />
      <xsd:element name="ChkNum" type="xsd:string" />
      <xsd:element name="CurAmt" type="aval:CurrencyAmount_Type" />
      <xsd:element name="ClientDt" type="xsd:string" />
      <xsd:element name="CustLoginId" type="xsd:string" />
      <xsd:element name="RqUID" type="aval:UUID_Type" />
      <xsd:element name="Version" type="xsd:string" />
      <xsd:element name="GovOrg" type="aval:OpenEnum_Type" />
      <xsd:element name="CurConvertRule" type="aval:OpenEnum_Type" />
      <xsd:element name="GovIssueIdentType" type="aval:OpenEnum_Type" />
      <xsd:element name="CurRate" type="xsd:decimal" />
      <xsd:element name="Channel" type="xsd:string" />
      <xsd:element name="ExpDt" type="xsd:string" />
      <xsd:element name="CurCode" type="xsd:string" />
      <xsd:element name="BankId" type="xsd:string" />
      <xsd:element name="StatusDesc" type="xsd:string" />
      <xsd:element name="KeyAcctId" type="xsd:string" />
      <xsd:element name="SessKey" type="xsd:string" />
      <xsd:element name="Desc" type="xsd:string" />
      <xsd:element name="RefType" type="aval:RefType_Type" />
      <xsd:element name="RefInfo" type="aval:RefInfo_Type" />
      <xsd:element name="MsgRqHdr" type="aval:MsgRqHdr_Type" />
      <xsd:element name="ClientApp" type="aval:ClientApp_Type" />
      <xsd:element name="BankInfo" type="aval:BankInfo_Type" />
      <xsd:element name="City" type="aval:City_Type" />
      <xsd:element name="StateProv" type="aval:StateProv_Type" />
      <xsd:element name="PostalCode" type="aval:PostalCode_Type" />
      <xsd:element name="Country" type="aval:Country_Type" />
      <xsd:element name="UserId" type="aval:UserId_Type" />
      <xsd:element name="CustId" type="aval:CustId_Type" />
      <xsd:element name="CustName" type="aval:CustName_Type" />
      <xsd:element name="Nickname" type="aval:Nickname_Type" />
      <xsd:element name="FirstName" type="aval:FirstName_Type" />
      <xsd:element name="LegalName" type="aval:LegalName_Type" />
      <xsd:element name="GovIssueIdent" type="aval:GovIssueIdent_Type" />
      <xsd:element name="GovOrgName" type="aval:GovOrgName_Type" />
      <xsd:element name="GovRank" type="aval:GovRank_Type" />
      <xsd:element name="IdentSerialNum" type="aval:IdentSerialNum_Type" />
      <xsd:element name="Status" type="aval:Status_Type" />
      <xsd:element name="Severity" type="aval:Severity_Type" />
      <xsd:element name="AdditionalStatus" type="aval:AdditionalStatus_Type" />
      <xsd:element name="TxCostAmt" type="aval:TxCostAmt_Type" />
      <xsd:element name="MsgRsHdr" type="aval:MsgRsHdr_Type" />
      <xsd:complexType name="CurrencyAmount_Type">
        <xsd:sequence>
          <xsd:element minOccurs="1" ref="aval:Amt" />
          <xsd:element minOccurs="0" ref="aval:CurCode" />
          <xsd:sequence minOccurs="0">
            <xsd:element minOccurs="0" ref="aval:CurRate" />
            <xsd:element minOccurs="0" ref="aval:CurConvertRule" />
          </xsd:sequence>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="RefInfo_Type">
        <xsd:sequence>
          <xsd:element ref="aval:RefType" />
          <xsd:element ref="aval:RefId" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="MsgRqHdr_Type">
        <xsd:sequence>
          <xsd:element minOccurs="0" ref="aval:ClientApp" />
          <xsd:element minOccurs="0" ref="avalv2:Channel" />
          <xsd:element minOccurs="0" ref="aval:BankInfo" />
          <xsd:element minOccurs="0" ref="avalv2:ClientDt" />
          <xsd:element minOccurs="0" ref="avalv2:IPAddr" />
          <xsd:element minOccurs="0" ref="avalv2:SessKey" />
          <xsd:element minOccurs="0" ref="aval:UserId" />
          <xsd:element minOccurs="0" ref="avalv2:KeyAcctId" />
          <xsd:element ref="avalv2:Reverse" />
          <xsd:element ref="avalv2:Language" />
          <xsd:element minOccurs="0" ref="avalv2:NextDay" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="ClientApp_Type">
        <xsd:sequence>
          <xsd:element minOccurs="0" ref="aval:Org" />
          <xsd:element minOccurs="0" ref="aval:Name" />
          <xsd:element minOccurs="0" ref="aval:Version" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="BankInfo_Type">
        <xsd:sequence>
          <xsd:element minOccurs="0" ref="aval:BankIdType" />
          <xsd:element ref="aval:BankId" />
          <xsd:element maxOccurs="unbounded" minOccurs="0" ref="aval:RefInfo" />
          <xsd:element minOccurs="0" ref="aval:Name" />
          <xsd:element minOccurs="0" ref="aval:BranchId" />
          <xsd:element minOccurs="0" ref="aval:BranchName" />
          <xsd:element minOccurs="0" ref="aval:City" />
          <xsd:element minOccurs="0" ref="aval:StateProv" />
          <xsd:element minOccurs="0" ref="aval:PostalCode" />
          <xsd:element minOccurs="0" ref="aval:Country" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="UserId_Type">
        <xsd:complexContent>
          <xsd:extension base="aval:CustId_Type">
            <xsd:sequence />
          </xsd:extension>
        </xsd:complexContent>
      </xsd:complexType>
      <xsd:complexType name="CustId_Type">
        <xsd:sequence>
          <xsd:element minOccurs="0" ref="aval:CustPermId" />
          <xsd:element minOccurs="0" ref="aval:CustLoginId" />
          <xsd:element minOccurs="0" ref="aval:GovIssueIdent" />
          <xsd:element maxOccurs="1" minOccurs="0" ref="aval:CustName" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="CustName_Type">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" ref="aval:LastName" />
          <xsd:element maxOccurs="1" minOccurs="0" ref="aval:FirstName" />
          <xsd:element maxOccurs="1" minOccurs="0" ref="aval:Nickname" />
          <xsd:element maxOccurs="1" minOccurs="0" ref="aval:LegalName" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="GovIssueIdent_Type">
        <xsd:sequence>
          <xsd:element ref="aval:GovIssueIdentType" />
          <xsd:element ref="aval:IdentSerialNum" />
          <xsd:element minOccurs="0" ref="aval:GovOrg" />
          <xsd:element minOccurs="0" ref="aval:GovOrgName" />
          <xsd:element minOccurs="0" ref="aval:GovRank" />
          <xsd:element minOccurs="0" ref="aval:StateProv" />
          <xsd:element minOccurs="0" ref="aval:Country" />
          <xsd:element minOccurs="0" ref="aval:Desc" />
          <xsd:element minOccurs="0" ref="aval:IssDt" />
          <xsd:element minOccurs="0" ref="aval:ExpDt" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="Status_Type">
        <xsd:sequence>
          <xsd:element minOccurs="1" ref="aval:StatusCode" />
          <xsd:element minOccurs="0" ref="aval:ServerStatusCode" />
          <xsd:element minOccurs="0" ref="aval:Severity" />
          <xsd:element minOccurs="0" ref="aval:StatusDesc" />
          <xsd:element minOccurs="0" ref="aval:ServerStatusDesc" />
          <xsd:element maxOccurs="unbounded" minOccurs="0" ref="aval:AdditionalStatus" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="AdditionalStatus_Type">
        <xsd:sequence>
          <xsd:element minOccurs="0" ref="aval:StatusCode" />
          <xsd:element minOccurs="0" ref="aval:ServerStatusCode" />
          <xsd:element minOccurs="0" ref="aval:Severity" />
          <xsd:element minOccurs="0" ref="aval:StatusDesc" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="TxCostAmt_Type">
        <xsd:sequence>
          <xsd:element minOccurs="1" ref="aval:CurAmt" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="MsgRsHdr_Type">
        <xsd:sequence>
          <xsd:element minOccurs="0" ref="aval:TxCostAmt" />
          <xsd:element minOccurs="0" ref="aval:EffDt" />
          <xsd:element minOccurs="0" ref="aval:RemainRec" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:simpleType name="LastName_Type">
        <xsd:restriction base="xsd:string" />
      </xsd:simpleType>
      <xsd:simpleType name="UUID_Type">
        <xsd:restriction base="xsd:string">
          <xsd:annotation>
            <xsd:documentation>UUID elements are Narrow Character with a maximum length of 36.</xsd:documentation>
          </xsd:annotation>
          <xsd:maxLength value="36" />
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="OpenEnum_Type">
        <xsd:restriction base="xsd:string" />
      </xsd:simpleType>
      <xsd:simpleType name="Identifier_Type">
        <xsd:annotation>
          <xsd:documentation>Object identifiers in the IFX Specification are of the
    data type "Identifier." This is a Narrow Character data
    type with a maximum length of 200.</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
          <xsd:maxLength value="200" />
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="RefType_Type">
        <xsd:restriction base="xsd:string" />
      </xsd:simpleType>
      <xsd:simpleType name="City_Type">
        <xsd:restriction base="xsd:string" />
      </xsd:simpleType>
      <xsd:simpleType name="StateProv_Type">
        <xsd:restriction base="xsd:string" />
      </xsd:simpleType>
      <xsd:simpleType name="PostalCode_Type">
        <xsd:restriction base="xsd:string" />
      </xsd:simpleType>
      <xsd:simpleType name="Country_Type">
        <xsd:restriction base="xsd:string" />
      </xsd:simpleType>
      <xsd:simpleType name="Nickname_Type">
        <xsd:restriction base="xsd:string" />
      </xsd:simpleType>
      <xsd:simpleType name="FirstName_Type">
        <xsd:restriction base="xsd:string" />
      </xsd:simpleType>
      <xsd:simpleType name="LegalName_Type">
        <xsd:restriction base="xsd:string" />
      </xsd:simpleType>
      <xsd:simpleType name="GovOrgName_Type">
        <xsd:restriction base="xsd:string" />
      </xsd:simpleType>
      <xsd:simpleType name="GovRank_Type">
        <xsd:restriction base="xsd:string" />
      </xsd:simpleType>
      <xsd:simpleType name="IdentSerialNum_Type">
        <xsd:restriction base="xsd:string" />
      </xsd:simpleType>
      <xsd:simpleType name="Severity_Type">
        <xsd:restriction base="xsd:string">
          <xsd:enumeration value="Error" />
          <xsd:enumeration value="Info" />
          <xsd:enumeration value="Warn" />
        </xsd:restriction>
      </xsd:simpleType>
    </xsd:schema>
    <xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn://grupoaval.com/xsd/ifx/v2/" xmlns:aval="urn://grupoaval.com/xsd/ifx/" xmlns:Q2="urn://grupoaval.com/xsd/ifx/v2/" xmlns:avalv2="urn://grupoaval.com/xsd/ifx/v2/">
      <xsd:import namespace="urn://grupoaval.com/xsd/ifx/" />
      <xsd:element name="ServerStatusDesc" type="xsd:string" />
      <xsd:element name="RefId" type="aval:Identifier_Type" />
      <xsd:element name="Code" type="xsd:string" />
      <xsd:element name="IPAddr" type="xsd:string" />
      <xsd:element name="ExpDt" type="xsd:dateTime" />
      <xsd:element name="Channel" type="xsd:string" />
      <xsd:element name="Nickname" type="xsd:string" />
      <xsd:element name="Amt" type="xsd:decimal" />
      <xsd:element name="CurAmt" type="aval:CurrencyAmount_Type" />
      <xsd:element name="Org" type="xsd:string" />
      <xsd:element name="SessKey" type="xsd:string" />
      <xsd:element name="Version" type="xsd:string" />
      <xsd:element name="ServerStatusCode" type="xsd:string" />
      <xsd:element name="Language" type="xsd:string" />
      <xsd:element name="NextDay" type="xsd:string" />
      <xsd:element name="BankIdType" type="aval:OpenEnum_Type" />
      <xsd:element name="IssDt" type="xsd:dateTime" />
      <xsd:element name="StatusDesc" type="xsd:string" />
      <xsd:element name="BranchId" type="xsd:string" />
      <xsd:element name="CustLoginId" type="xsd:string" />
      <xsd:element name="RemainRec" type="xsd:boolean" />
      <xsd:element name="EffDt" type="xsd:dateTime" />
      <xsd:element name="KeyAcctId" type="xsd:string" />
      <xsd:element name="CurCode" type="xsd:string" />
      <xsd:element name="BankId" type="xsd:string" />
      <xsd:element name="Reverse" type="xsd:boolean" />
      <xsd:element name="CurConvertRule" type="aval:OpenEnum_Type" />
      <xsd:element name="StatusCode" type="xsd:long" />
      <xsd:element name="Desc" type="xsd:string" />
      <xsd:element name="GovIssueIdentType" type="aval:OpenEnum_Type" />
      <xsd:element name="GovOrg" type="aval:OpenEnum_Type" />
      <xsd:element name="CustPermId" type="xsd:string" />
      <xsd:element name="Name" type="xsd:string" />
      <xsd:element name="ChkNum" type="xsd:string" />
      <xsd:element name="BranchName" type="xsd:string" />
      <xsd:element name="ClientDt" type="xsd:string" />
      <xsd:element name="RqUID" type="aval:UUID_Type" />
      <xsd:element name="CurRate" type="xsd:decimal" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ModifyOverdraftLineRequest">
    <wsdl:part element="v1:ModifyOverdraftLineRequest" name="parameters" />
  </wsdl:message>
  <wsdl:message name="ModifyOverdraftLineResponse">
    <wsdl:part element="v1:ModifyOverdraftLineResponse" name="parameters" />
  </wsdl:message>
  <wsdl:portType name="SrvOverdraftLine_ModifyOverdraftLine">
    <wsdl:operation name="ModifyOverdraftLine">
      <wsdl:input message="v1:ModifyOverdraftLineRequest" />
      <wsdl:output message="v1:ModifyOverdraftLineResponse" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SrvOverdraftLineSOAP_ModifyOverdraftLine" type="v1:SrvOverdraftLine_ModifyOverdraftLine">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="ModifyOverdraftLine">
      <soap:operation soapAction="urn://grupoaval.com/prodschnsmngt/v1/ModifyOverdraftLine" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SrvOverdraftLine_ModifyOverdraftLine">
    <wsdl:port binding="v1:SrvOverdraftLineSOAP_ModifyOverdraftLine" name="SrvOverdraftLineSOAP">
      <soap:address location="https://brokerbpop:7949/prodschnsmngt/SSL/ModifyOverdraftLine" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
