openapi: 3.0.0
info:
  title: SrvGetContactAccountAST
  description: Esta API permite la consulta de un contacto específico en la agenda de AST para transferencias.
  contact:
    email: notificacionESB@bancopopular.com.co
  version: 1.0.0
servers:
- url: https://10.200.157.5:7859/customerManagement/v1/Affiliation
paths:
  /GetContact:
    post:
      tags:
      - GetContact
      summary: Consulta un contacto en la agenda de AST para transferencias
      description: Consulta un contacto específico en la agenda de AST para transferencias
      operationId: postGetContactAccount
      parameters:
      - name: X-RqUID
        in: header
        description: Identificador unico del mensaje
        required: true
        schema:
          maxLength: 32
          minLength: 1
          type: string
        example: "201901160925"
      - name: X-Channel
        in: header
        description: Canal origen de consumo de la transaccion
        required: true
        schema:
          maxLength: 20
          minLength: 1
          type: string
          enum:
          - BM
          - PB          
        example: BM
      - name: X-CompanyId
        in: header
        description: Codigo de empresa que realiza la invocacion
        required: true
        schema:
          maxLength: 10
          minLength: 1
          type: string
        example: "0002"
      - name: X-GovIssueIdentType
        in: header
        description: Tipo de identificación emitida por el gobierno del pais
        required: false
        schema:
          maxLength: 20
          minLength: 1
          type: string
        example: "1"
      - name: X-IdentSerialNum
        in: header
        description: Numero de identificacion de la persona que realiza la invocación
        required: true
        schema:
          maxLength: 20
          minLength: 1
          type: string
        example: "340141001"
      - name: X-IPAddr
        in: header
        description: Ip de dispositivo
        required: true
        schema:
          maxLength: 15
          minLength: 1
          type: string
          format: ipv4
        example: "179.1.89.18"
      - name: X-SessKey
        in: header
        description: Código de sesión
        required: false
        schema:
          maxLength: 99
          minLength: 1
          type: string
        example: "65tf76t7f7td7fdo5dtyg877hijyio89"
      - name: X-Version
        in: header
        description: Version del servicio
        required: false
        schema:
          maxLength: 20
          minLength: 1
          type: string
        example: "1.0"
      - name: X-KeyAcctId
        in: header
        required: false
        schema:
          type: string
          maxLength: 15
          minLength: 1
        description: Llave de identificación de cuenta
        example: "2"              
      - name: X-BankId
        in: header
        required: true
        schema:
          type: string
          maxLength: 99
          minLength: 1
        description: Identificador del banco
        example: "0002"
      - name: X-BankIdType
        in: header
        required: true
        schema:
          type: string
          maxLength: 1
          minLength: 1
        description: Jornada de la Transaccion
        example: "1"
      - name: X-BranchId
        in: header
        required: true
        schema:
          type: string
          maxLength: 10
          minLength: 1
        description: Identificador de la oficina
        example: "001"
      - name: X-ClientDt
        in: header
        description: Fecha de transacción - AAAA-MM-DDThh:mm:ss
        required: true
        schema:
          type: string
          format: date-time
        example: 2024-08-09T20:00:00
      - name: X-NextDay
        in: header
        description: Fecha de transacción - AAAA-MM-DDThh:mm:ss
        required: true
        schema:
          type: string
          format: date-time
        example: 2024-08-09T20:00:00
      - name: X-Reverse
        in: header
        description: Indicador de Reverso
        required: true
        schema:
          type: boolean
        example: false
      - name: X-Language
        in: header
        description: "especifica lenguaje usado, sigue el estandar ISO 639 mas un guion mas el codigo de pais segun la norma ISO 3166"
        required: true
        schema:
          maxLength: 5
          minLength: 5
          type: string
        example: es_CO
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetContactAccountRequest'
        required: true
      responses:
        "201":
          description: Transaccion Exitosa
          headers:
            X-ApprovalId:
              description: Numero de autorizacion de la transaccion.
              schema:
                type: string
            X-RqUID:
              description: Identificador unico de la invocacion.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetContactAccountResponse'
        "206":
          description: Error en la transaccion
          headers:
            X-ApprovalId:
              description: Numero de autorizacion de la transaccion.
              schema:
                type: string
            X-RqUID:
              description: Identificador unico de la invocacion.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetContactAccountResponseBusinessError'
        "400":
          description: Peticion incorrecta
          headers:
            X-ApprovalId:
              description: Numero de autorizacion de la transaccion.
              schema:
                type: string
            X-RqUID:
              description: Identificador unico de la invocacion.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetContactAccountResponseError'
        "500":
          description: Ha ocurrido un error en la invocacion
          headers:
            X-ApprovalId:
              description: Numero de autorizacion de la transaccion.
              schema:
                type: string
            X-RqUID:
              description: Identificador unico de la invocacion.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetContactAccountResponseError'
        "501":
          description: Operación no implementada
          headers:
            X-ApprovalId:
              description: Numero de autorizacion de la transaccion.
              schema:
                type: string
            X-RqUID:
              description: Identificador unico de la invocacion.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetContactAccountResponseError'
        "503":
          description: Servidor no disponible
          headers:
            X-ApprovalId:
              description: Numero de autorizacion de la transaccion.
              schema:
                type: string
            X-RqUID:
              description: Identificador unico de la invocacion.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetContactAccountResponseError'
        "504":
          description: Timeout
          headers:
            X-ApprovalId:
              description: Numero de autorizacion de la transaccion.
              schema:
                type: string
            X-RqUID:
              description: Identificador unico de la invocacion.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetContactAccountResponseError'
        "404":
          description: Recurso no existe
          headers:
            X-ApprovalId:
              description: Numero de autorizacion de la transaccion.
              schema:
                type: string
            X-RqUID:
              description: Identificador unico de la invocacion.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetContactAccountResponseError'
        "412":
          description: RqUID es requerido
          headers:
            X-ApprovalId:
              description: Numero de autorizacion de la transaccion.
              schema:
                type: string
            X-RqUID:
              description: Identificador unico de la invocacion.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetContactAccountResponseError'
        "408":
          description: Timeout del backend
          headers:
            X-ApprovalId:
              description: Numero de autorizacion de la transaccion.
              schema:
                type: string
            X-RqUID:
              description: Identificador unico de la invocacion.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetContactAccountResponseError'
        "420":
          description: Error en el backend
          headers:
            X-ApprovalId:
              description: Numero de autorizacion de la transaccion.
              schema:
                type: string
            X-RqUID:
              description: Identificador unico de la invocacion.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetContactAccountResponseError'
components:
  schemas:
    GetContactAccountRequest:
      type: object
      properties:
        ContactInfi:
          $ref: '#/components/schemas/ContactInfo'
    GetContactAccountResponse:
      type: object
      properties:
        MsgRsHdr:
          $ref: '#/components/schemas/MsgRsHdr'
        ContactInfo:
          $ref: '#/components/schemas/ContactInfo'
    GetContactAccountResponseBusinessError:
      type: object
      properties:
        MsgRsHdr:
          $ref: '#/components/schemas/MsgRsHdr'
    GetContactAccountResponseError:
      type: object
      properties:
        MsgRsHdr:
          $ref: '#/components/schemas/MsgRsHdr'
    MsgRsHdr:
      required:
      - Status
      type: object
      properties:
        Status:
          $ref: '#/components/schemas/Status'
    Status:
      required:
      - Severity
      - StatusCode
      type: object
      properties:
        StatusCode:
          maxLength: 9
          minLength: 1
          type: string
          description: Codigo de respuesta
          example: "0"
        ServerStatusCode:
          maxLength: 10
          minLength: 1
          type: string
          description: Codigo de respuesta del servidor
          example: "0"
        Severity:
          type: string
          maxLength: 7
          minLength: 4
          description: Codigo de severidad de la respuesta
          enum:
          - Info
          - Warning
          - Error
          example: Info
        StatusDesc:
          maxLength: 100
          minLength: 1
          type: string
          description: Explicacion asociada al statusCode
          example: Transaccion Exitosa (o Transaccion rechazada en caso de error)
        AdditionalStatus:
          $ref: '#/components/schemas/AdditionalStatus'
        EndDt:
          type: string
          description: "Indica fecha de finalizacion, terminacion, etc."
          format: date-time
          example: 2026-03-05T15:22:30
    AdditionalStatus:
      type: object
      properties:
        StatusCode:
          maxLength: 9
          minLength: 1
          type: string
          description: Codigo de respuesta
          example: "0"
        ServerStatusCode:
          maxLength: 10
          minLength: 1
          type: string
          description: Codigo de respuesta del servidor
          example: "0"
        Severity:
          type: string
          maxLength: 7
          minLength: 4
          description: Codigo de severidad de la respuesta
          enum:
          - Info
          - Warning
          - Error
          example: Info
        StatusDesc:
          maxLength: 100
          minLength: 1
          type: string
          description: Explicacion asociada al statusCode
          example: Transaccion Exitosa (o Transaccion rechazada en caso de error)
    DepAcctId:
      type: object
      properties:
        AcctId:
          maxLength: 25
          minLength: 1
          type: string
          description: Identificador de una cuenta
          example: "500771619489"
        AcctType:
          type: string
          maxLength: 3
          minLength: 1
          description: "Tipo de cuenta AHO: Ahorros COR: Corriente DPE: Depósito electrónico"
          enum:
          - AHO
          - COR
          - DPE
          example: AHO
        BankInfo:
          $ref: '#/components/schemas/BankInfo'
    DepAcctIdTo:
      type: object
      properties:
        DepAcctId:
          $ref: '#/components/schemas/DepAcctId'
    ContactInfo:
      type: object
      properties:
        ContactIda:
          type: integer
          maximum: 9999999999
          minimum: 1
          description: Identificador del contacto dentro de la agenda
          example: "1"
        ContactName:
          type: string
          maxLength: 99
          minLength: 1
          description: Nombre del contacto
          example: Javier Mendoza
        NickName:
          type: string
          maxLength: 99
          minLength: 1
          description: Alias del contacto
          example: Javier BPop
        GovIssueIdent:
          $ref: '#/components/schemas/GovIssueIdent'
        DepAcctIdTo:
          $ref: '#/components/schemas/DepAcctIdTo'
        Favorite:
          type: boolean
          description: Indica si se marca como favorita o no
          example: true
      required:
      - ContactId
    BankInfo:
      type: object
      properties:
        BankId:
          type: string
          maxLength: 9
          minLength: 1
          description: Código del banco destino.
          example: "2"
        Name:
          type: string
          maxLength: 99
          minLength: 1
          description: Nombre del banco destino.
          example: BANCO POPULAR
    GovIssueIdent:
      type: object
      properties:
        GovIssueIdentType:
          type: string
          maxLength: 9
          minLength: 1
          description: "Tipo de identificacion emitida por el gobierno del pais. CC - Cedula de ciudadania. CE: Cedula extrangeria NIT_NAT: NIT Persona Natural. NIT_JUR: NIT Persona Juridica. PAS: Pasaporte. RC: Registro civil. TI: Tarjeta de identidad. FD: Fideicomiso"
          enum:
          - CC
          - CE
          - NIT_NAT
          - NIT_JUR
          - PAS
          - RC
          - TI
          - FD
          example: CC
        IdentSerialNum:
          type: string
          maxLength: 20
          minLength: 1
          description: Número de identificación del contacto
          example: "1040735988"
